name: Build API Documentation
on:
  workflow_dispatch

jobs:
  build-api-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Javadocs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: api:javadoc
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: api-documentation
          FOLDER: api/build/docs/javadoc
          CLEAN: true
          CLEAN_EXCLUDE: '["CNAME"]'
          SINGLE_COMMIT: true
